package com.dxc.gdr.model;

public enum EPermission {
    LIRE_RECLAMATIONS,
    CREER_RECLAMATIONS,
    MODIFIER_RECLAMATIONS,
    SUPPRIMER_RECLAMATIONS,
    ASSIGNER_RECLAMATIONS,
    LIRE_UTILISATEURS,
    CREER_UTILISATEURS,
    MODIFIER_UTILISATEURS,
    SUPPRIMER_UTILISATEURS,
    GERER_ACCES,
    CONSULTER_RAPPORTS
}
