spring.application.name=gdr

# Configuration de la base de données (Doit correspondre au Docker Compose)
spring.datasource.url=jdbc:postgresql://localhost:5433/db_reclamations
spring.datasource.username=admin_gdr
spring.datasource.password=password_gdr
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Sécurité JWT (Gardez la clé secrète complexe)
gdr.app.jwtSecret=MaCleSecreteDXCReclamations2024TresLongueEtSecure
gdr.app.jwtExpirationMs=86400000